### ISSUE TITLE
broken example for file handling

### ISSUE THREAD

**Issue by neihcnim** [typeiii/jquery-csv#143]
Consider http://typeiii.github.io/jquery-csv/examples/file-handling.html

## Environment

- Platform: Safari and FIrefox

## Steps to reproduce

After the csv file is uploaded, nothing happens.

## Expected behaviour

The csv data should be parsed.

## Actual behaviour

Nothing happens

**Comment by evanplaice** [comment]
Thank you for the report, I'm on it

**Comment by dntzbgh** [comment]
Adding 
`var global=window;` 
to helpers.js solved the issue

**Comment by evanplaice** [comment]
Fixed in [v1.0.20](https://github.com/evanplaice/jquery-csv/releases/tag/v1.0.20)

The JSDelivr CDN takes its sweet time to flush the cache. It should be working by tomorrow.

**Comment by XenonofArcticus** [comment]
FWIW, the CDN still doesn't seem to be flushed. 
[http://evanplaice.github.io/jquery-csv/examples/helpers.js](http://evanplaice.github.io/jquery-csv/examples/helpers.js
)
still lacks the global declaration as of today.
